"""changed Column type

Revision ID: 9be49dfc6123
Revises: 4b0c55357dbe
Create Date: 2024-03-05 11:36:25.536786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be49dfc6123'
down_revision = '4b0c55357dbe'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ### ADD THIS LINE ###
    op.execute("ALTER TABLE links ALTER COLUMN user_id TYPE integer USING (user_id::integer)")

    ### REMOVE THIS SECTION ###
    # op.alter_column('links', 'user_id',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    ### END REMOVAL ###
    
    ### LEAVE UNCHANGED ###
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.alter_column('links', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
