"""refactored models

Revision ID: fc8ec9c4ffd4
Revises: 857785e6a7e7
Create Date: 2024-03-05 11:01:15.495871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8ec9c4ffd4'
down_revision = '857785e6a7e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
